[package]
name = "example-hello-world"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
axum =  "0.7.4"
axum-test-helper = { path = "../../../axum-test-helper/"} 
tokio = { version = "1.0", features = ["full"] }
